apiVersion: v1
kind: Pod
metadata:
  name: recover-pv-pod
spec:
  volumes:
    - name: recover-pv-storage
      persistentVolumeClaim:
        claimName: recover-pv-claim
  containers:
    - name: recover-pv-container
      image: alpine
      command: [ "/bin/ash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - mountPath: "/mnt"
          name: recover-pv-storage
